### ISSUE TITLE
Add info about rgba coloring to Grid docs

### ISSUE THREAD

**Issue by amacneil** [foxglove/schemas#67]
See: https://foxglove.dev/docs/studio/messages/grid

- How do I create a greyscale grid?
- How do I create an rgb or rgba grid?

**Comment by jtbandes** [comment]
Related: https://github.com/foxglove/schemas/issues/32

**Comment by amacneil** [comment]
[FG-1406](https://linear.app/foxglove/issue/FG-1406/document-field-names-for-foxglovegrid-and-foxglovepointcloud)
